# Computing with images

We have seen in the last chapter that images exist in the form of Numpy arrays. We will here see different types of image processing computations that we can do with such arrays such as arithmetic operations, combining images etc.

We have seen in the last chapter that we could create images using e.g. the ```np.random.random``` function. Let's create two tiny images:

In [5]:
import numpy as np

image1 = np.ones((3,5))
image1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
image2 = np.random.random((3,5))
image2

array([[0.27194417, 0.30500551, 0.88970898, 0.74560188, 0.91738941],
       [0.98418878, 0.2635199 , 0.25729652, 0.22427242, 0.39387982],
       [0.59095273, 0.90222827, 0.4722848 , 0.05913885, 0.96609068]])

## Simple calculus

As a recap from last chapter, we have seen that we can do arithemtics with images just as we would with simple numbers:

In [8]:
image1_plus = image1 + 3
image1_plus

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

This is valid for all basis operations like addition, multiplication etc. Even raising to a given power works:

In [27]:
image1_plus ** 2

array([[16., 16., 16., 16., 16.],
       [16., 16., 16., 16., 16.],
       [16., 16., 16., 16., 16.]])

## Combining images

If images have the same size, we can here again treat them like simple numbers and do maths with them: again addition, multiplication etc. For example:

In [28]:
image1 + image2

array([[1.27194417, 1.30500551, 1.88970898, 1.74560188, 1.91738941],
       [1.98418878, 1.2635199 , 1.25729652, 1.22427242, 1.39387982],
       [1.59095273, 1.90222827, 1.4722848 , 1.05913885, 1.96609068]])

## Functions pixel by pixel

In addition of allowing us to create various types of arrays, Numpy also provides us functions that can operate on arrays. In many cases, the input is an image and the output is an image of the same size where *a given function has been applied to each individual pixel*. 

For example we might want to apply a log function to an image to reduce the range of values that pixels can take. Here we would use the ```np.log``` function:

In [12]:
np.log(image2)

array([[-1.3021585 , -1.18742543, -0.11686086, -0.29356349, -0.08622324],
       [-0.01593755, -1.3336264 , -1.35752608, -1.49489381, -0.93170945],
       [-0.52601924, -0.10288772, -0.75017308, -2.82786728, -0.03449758]])

As we can see the input image had 3 rows and 5 columns and the output image has the same dimensions. You can find many functions in Numpy that operate this way e.g. to take an exponential (```np.exp()```), to do trigonometry (```np.cos()```, ```np.sin()```) etc.

## Image statistics

Another type of functions takes an image as input but returns an output of a different size by computing a statistic on the image or parts of it. For example we can compute the average of *all* ```image2``` pixel values:

In [32]:
np.mean(image2)

0.5495668473697417

Or we can specify that we want to compute the mean along a certain dimension of the image, in 2D along columns or rows. Let's keep in mind what ```image2``` is:

In [30]:
image2

array([[0.27194417, 0.30500551, 0.88970898, 0.74560188, 0.91738941],
       [0.98418878, 0.2635199 , 0.25729652, 0.22427242, 0.39387982],
       [0.59095273, 0.90222827, 0.4722848 , 0.05913885, 0.96609068]])

Now we take the average over columns, which means along the first axis or ```axis=0```:

In [31]:
np.mean(image2, axis=0)

array([0.61569523, 0.49025123, 0.53976343, 0.34300438, 0.75911997])

The same logic applies to all other statistical functions such as taking the minium (```np.min()```), the maxiumum (```np.max()```), standard deviation (```np.std()```), median (```np.median()```) etc.

Note that most of this function can also be called directly on the Numpy array variable. For example

In [33]:
np.std(image2)

0.31182981411327126

and

In [34]:
image2.std()

0.31182981411327126

are completely equivalent. In the latter case using the dot notation, you might hear that ```std()``` is a *method* of ```image2```.

In [ ]:
Finally we might want to have a look at the actual distribution of pixel values. For this 

## Exercise

From the ```numpy.random``` module, find a function that generates **Poisson** noise and creata a 4x9 image. Compute its mean and standard deviation.